### ISSUE TITLE
Add arrows to map routes 

### ISSUE THREAD

**Issue by GrandSuccess87** [activist-org/activist#893] opened 2024-06-01 17:23 UTC
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue will focus on  adding arrows for each route profile: walking, biking, driving. 

This component lives in [frontend/components/media/MediaMap.vue](https://github.com/activist-org/activist/blob/main/frontend/components/media/MediaMap.vue) and we're using the extension  [maplibre-gl-directions](https://github.com/maplibre/maplibre-gl-directions).

### Contribution

Happy to pair up with someone on this or tackle it myself :))

**Comment by rabelmervin** [comment] 2024-06-02 06:58
Hi Madam @GrandSuccess87, I'm interested in solving this issue. Can we group together and solve this ??? Looking forward to your response. Thank you :)

**Comment by andrewtavis** [comment] 2024-06-02 07:17
Hey @rabelmervin 👋 Assigned the issue to you :) You can see the added arrow that we're looking for by using the directions on [this maplibre-gl-directions example](https://maplibre.org/maplibre-gl-directions/#/examples/show-routes'-directions). The source code with the needed change for it is [here](https://github.com/maplibre/maplibre-gl-directions/blob/main/demo/src/examples/5%20Show%20Routes'%20Directions.svelte), and as @GrandSuccess87 said we'd like the change to go into [frontend/components/media/MediaMap.vue](https://github.com/activist-org/activist/blob/main/frontend/components/media/MediaMap.vue).

Let us know if there's any further help needed!

**Comment by rabelmervin** [comment] 2024-06-02 08:15
Thanks Sir @andrewtavis for your response. So The issue is to add arrows when two points are selected in the map . Right ???

**Comment by andrewtavis** [comment] 2024-06-02 08:23
Ah interesting, I was thinking we'd just do a single type of arrow and use the default. The directions already change color based on the profile, and adding in a white arrow as is done in the example would be fine for me. How about we start with that for this issue, and if we want to do specific arrows for specific profiles we can change that in a later issue?

Let me know if this is what you were thinking, @GrandSuccess87!

**Comment by rabelmervin** [comment] 2024-06-05 14:43
Hi sir @andrewtavis, I cant able to run the vue file on my ide's. I tried many but can't.

**Comment by andrewtavis** [comment] 2024-06-05 15:33
Hey @rabelmervin 👋 If you give VS Code a shot, it should work :)

**Comment by andrewtavis** [comment] 2024-06-05 18:25
Welcome, @rabelmervin! Let us know if you need further support! :)

**Comment by andrewtavis** [comment] 2024-06-08 11:28
Bring the conversation back to here from email, @rabelmervin :) I'm realizing this is a bit more involved, but I think we can get it to work :)

- Firstly we need an image for this. Let's go ahead and get [the PNG image that was used in the original example](https://github.com/maplibre/maplibre-gl-directions/blob/main/demo/src/assets/map/images/direction-arrow.png) and we can put it in [frontend/public/icons](https://github.com/activist-org/activist/tree/main/frontend/public/icons) (`dirrection-arrow.png` as it's named is fine)
- We then need to import the image as is done in the example [here](https://github.com/maplibre/maplibre-gl-directions/blob/05d4c1e244a237373280e9ab292ef56ee4bf57e0/demo/src/examples/5%20Show%20Routes'%20Directions.svelte#L10C3-L10C85)
- We then load the image into the map as is done in the example [here](https://github.com/maplibre/maplibre-gl-directions/blob/05d4c1e244a237373280e9ab292ef56ee4bf57e0/demo/src/examples/5%20Show%20Routes'%20Directions.svelte#L33)
- We then create a layers object and add the image to it like in the example [here](https://github.com/maplibre/maplibre-gl-directions/blob/05d4c1e244a237373280e9ab292ef56ee4bf57e0/demo/src/examples/5%20Show%20Routes'%20Directions.svelte#L39)
- And then we need to add the layer to the map as is done in the example [here](https://github.com/maplibre/maplibre-gl-directions/blob/05d4c1e244a237373280e9ab292ef56ee4bf57e0/demo/src/examples/5%20Show%20Routes'%20Directions.svelte#L61)

Let me know if there are other questions on this, @rabelmervin! Happy to help further. Let's keep the discussion on GitHub though so the rest of the community can follow :)

**Comment by rabelmervin** [comment] 2024-06-08 11:41
Thanks for helping me @andrewtavis.

**Comment by andrewtavis** [comment] 2024-06-08 11:44
Very welcome, @rabelmervin!

**Comment by rabelmervin** [comment] 2024-06-08 13:43
modifications successfully made @andrewtavis but, It has some errors here and there is it okay ???

**Comment by andrewtavis** [comment] 2024-06-08 16:05
You're welcome to open a PR and I'll help with the errors, @rabelmervin :)

**Comment by rabelmervin** [comment] 2024-06-12 12:55
hi sir @andrewtavis, I apologize for making the pr late. successfully made PR. could you tell me the mistakes that I  made ???

**Comment by rabelmervin** [comment] 2024-06-12 16:13
oh sorry sir @andrewtavis, now i made it right.

**Comment by andrewtavis** [comment] 2024-06-30 12:57
Closed by #900 🙌 This map sure is coming along 😊 Thanks for making the issue, @GrandSuccess87, and thanks for the initial implementation, @rabelmervin!

**Closed by andrewtavis** 2024-06-30 12:57 UTC
Labels: feature, help wanted, good first issue
