### ISSUE TITLE
TypeScript Error in `BtnLabeled.vue`

### ISSUE THREAD

**Issue by TeddyGavi** [activist-org/activist#233] opened 2023-07-16 13:30 UTC
### Terms

- [X] I have searched [open and closed issues](https://github.com/activist-org/activist/issues?q=is%3Aissue)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

Error as follows:

> components/Btn/BtnLabeled.vue:45:5 - error TS2322: Type 'string | null' is not assignable to type 'string | undefined'.                                                                       
  Type 'null' is not assignable to type 'string | undefined'. 

![Screenshot from 2023-07-16 06-15-01](https://github.com/activist-org/activist/assets/102203363/a118cff6-243a-48d3-ac6f-71f340cf3e51)

A recommendation would be to make the string optional. However, from my understanding alt text is used by screen readers. :smile:  

@luuu-xu do you have thoughts on this?

Continues issue #211.

**Comment by versacodes** [comment] 2023-07-17 02:08
What is the value of alternateText? Maybe the error shows because of  alternateText: string | null in defineProps. Try string | undefined instead.

**Comment by luuu-xu** [comment] 2023-07-17 18:30
Yes, maybe it should be declared as `alternateText?: string`. 

The purpose of `BtnLabeled`'s `alternateText` prop is to add optional `aria-label` text string to our buttons where a more detailed explanation can be provided (with i18n) comparing to just having an ambiguous text inside of the button. 

By the way, @TeddyGavi  how did you set up your project that you have TS checkings running correctly in editor? I am having trouble with my project where all of these props yell at me so I couldn't declare my props right. See: https://github.com/activist-org/activist/issues/213#issuecomment-1634877949

Your help will be greatly greatly appreciated because I want them stop yelling at me. 😭

**Comment by luuu-xu** [comment] 2023-07-17 18:39
Right, so I have also found that in our landing page, the "Our supporters" section, which comes from `LandingPageContent  contentPosition="top"`, since it does not have a image on the side, ts says we need to pass in `imageURL` and `altText` props. But in fact we don't need to, so we should declare these two props as **optional** too.

**Comment by andrewtavis** [comment] 2023-07-17 18:43
This makes sense, @luuu-xu! As far as the errors - just checking - have you installed the VS Code extensions that are listed in the [.vscode/extensions.json](https://github.com/activist-org/activist/blob/main/.vscode/extensions.json) file? That is if you’re using VS Code :)

**Comment by luuu-xu** [comment] 2023-07-17 19:06
@andrewtavis Yes I have these extensions installed, and I also followed Volar's Takeover Mode instructions and still TS is not working properly.

**Comment by TeddyGavi** [comment] 2023-07-18 05:38
Hey @luuu-xu Thank you for your valuable insight! And I am glad you got vscode working! something I just recently discovered is in the command palette using `shift + ctrl + p` (default hotkey set up) and selecting `Developer: Reload Window`  also works well to reset vscode after installing or reconfiguring settings/extensions. Although resetting is certainly safer.

>  ...ts says we need to pass in imageURL and altText props. But in fact we don't need to, so we should declare these two props as optional too.

I agree! :+1: 

I am curious, do you see an error in vscode or from `yarn nuxi typecheck` ? I do not see the error but I did notice the intrinsic value is optional and `string | undefined` for those attributes. Just as @versacodes had mentioned earlier. Regardless, they should still be marked optional as it is better to be explicit in my opinion.

**Comment by andrewtavis** [comment] 2023-07-18 06:41
> @andrewtavis Yes I have these extensions installed, and I also followed Volar's Takeover Mode instructions and still TS is not working properly.

I've now updated #227 with a direction that we should also document the extensions in the first steps section of the contributing guidelines to make sure this isn't as much of an issue in the future :)

Would someone like to do a PR for this? Maybe @versacodes in recognition of the original suggestion? 😊

**Comment by luuu-xu** [comment] 2023-07-18 15:53
> I am curious, do you see an error in vscode or from yarn nuxi typecheck ? I do not see the error but I did notice the intrinsic value is optional and string | undefined for those attributes. 

So I ran `yarn nuxi typecheck` and **did not** see this error neither. But I saw the error while I am on our landing page with console open. Apparently it is a Vue warning saying it's missing required prop. Please see screen shot of the console errors:

<img width="761" alt="Screenshot 2023-07-18 at 11 52 22" src="https://github.com/activist-org/activist/assets/97932191/f867d5b7-3853-4781-9a96-3397d3959e96">

**Comment by luuu-xu** [comment] 2023-07-18 16:54
@TeddyGavi Have you also noticed that we have errors (both from `yarn nuxi typecheck` and console) for `BtnLabeled.vue`'s supposedly optional  `iconSize` prop? 

I think we need to redeclare the iconSize as optional with a default value following the instructions here [Default props values when using type declaration ](https://vuejs.org/api/sfc-script-setup.html#default-props-values-when-using-type-declaration). 

And we should also mention this in our contributing ts documentations. @andrewtavis What do you think?

**Comment by andrewtavis** [comment] 2023-07-18 17:06
Redeclaring with default and optional sounds good to me, @luuu-xu :) As far as contributing documentation, you mean also note that this should be the standard in the TS section for properties? If optional, always declare with a default?

**Comment by luuu-xu** [comment] 2023-07-18 17:22
> If optional, always declare with a default?

@andrewtavis I don't mean always declare optional prop with a default. It is said in the Vue documentation that we need to use `withDefaults()` to declare a prop with a default value. I have tried it and it successfully eliminated all of the annoying ts errors from `BtnLabeled`. 

So I think we should probably include that piece of documentation in our docs pointing out that `withDefaults()` is needed for a prop with a default value otherwise we will have ts errors.

Before:

```
defineProps<{
  cta: boolean;
  linkTo: string;
  label: string;
  fontSize: "xs" | "sm" | "base" | "lg" | "xl" | "2xl" | "3xl";
  leftIcon?: string;
  rightIcon?: string;
  iconSize: {
    default: "1em";
    type: string;
    required: false;
  };
  alternateText: string | null;
}>();
```
After:

```
  export interface Props {
    cta: boolean;
    linkTo: string;
    label: string;
    fontSize: "xs" | "sm" | "base" | "lg" | "xl" | "2xl" | "3xl";
    leftIcon?: string;
    rightIcon?: string;
    iconSize?: string;
    alternateText?: string;
  }

  const props = withDefaults(defineProps<Props>(), {
    iconSize: "1em",
  });
```

**Comment by TeddyGavi** [comment] 2023-07-18 17:26
Hey, @luuu-xu when is the last time you regenerated the types locally? I had this error originally as well, however, once I generated new types locally many errors were removed. I currently have 1 error present in `BtnLabeled.vue` I did find the docs you mentioned and thought it was strange that this error went away.

I am not exactly sure what is going on but here is what I did: 

After TS config:
1. run `yarn nuxi typecheck` 
- over 50 errors present.
- Realized that the types were statically generated, and only done at build time, to create types locally `nuxi prepare` is needed. [Take a look here](https://nuxt.com/docs/api/commands/prepare)
- ran `yarn run postinstall` -> types generated
- Now I have 33 errors :worried: 

I do agree that the `withDefaults` should be included. I updated the docs to include the new workflow and intentionally left out the default issue as generating the new types seemed to solve it for me.

**Comment by luuu-xu** [comment] 2023-07-18 17:43
> Now I have 33 errors 😟

@TeddyGavi I immediately went ahead and tried your steps. Before running `yarn run postinstall` I have 66 errors, after running it, types are generated, I still have 66 errors...

**Comment by TeddyGavi** [comment] 2023-07-18 17:58
I pulled down the most recent repo, and cleaned the cache (removed .output and .nuxt) and re-ran the commands, (I tried running `npx vue-tsc` directly also) I still have 33 errors...this is an issue :worried: Not sure where to go from here. 

@andrewtavis or @versacodes  How many errors are present in the output from you running `yarn nuxi typecheck`?

**Comment by andrewtavis** [comment] 2023-07-18 22:23
@TeddyGavi and @luuu-xu, I'm at 59 errors... Super confusing 🤨 And this didn't change after I ran `npx nuxi prepare` and `yarn run postinstall` before again running `yarn nuxi typecheck`.

**Comment by TeddyGavi** [comment] 2023-07-18 22:34
Well, It appears that generating the types doesn't affect the type inference. I wonder if this is due to runtime checking...either way We shouldn't have that much of a difference between error results. Given maybe one or two PR's between local repos, I would expect a 1 or 2 error difference. Not a 30+ or 7+. Could this have something to do with Docker? I am not and was not running my code in Docker currently, just checking errors with vs code and typecheck. Thoughts?

**Comment by andrewtavis** [comment] 2023-07-18 22:39
Docker should be consistent. Maybe something for the next dev sync is really to go into the extensions setup, as those could be effecting error detection? Let me do the first part of #227 right now where I'll just dump in the related extensions that I have for activist :)

**Comment by andrewtavis** [comment] 2023-07-18 22:40
Keeping this issue open for now for the discussion, but will close #234 😊

**Comment by andrewtavis** [comment] 2023-07-18 23:23
Just finished #227 (feedback welcome) to add in the `First steps as a contributor` section as well as the VS Code extensions into the [dev env setup notes in the contributing guide](https://github.com/activist-org/activist/blob/main/CONTRIBUTING.md#dev-env) and [readme](https://github.com/activist-org/activist#environment-setup-). Let me know if anyone has any suggestions for those sections and if any ideas for extensions come up! :)

**Comment by andrewtavis** [comment] 2023-07-20 20:07
@TeddyGavi and @luuu-xu: can you both try out `yarn nuxi typecheck` with the extensions detailed in the [dev env setup notes in the contributing guide](https://github.com/activist-org/activist/blob/main/CONTRIBUTING.md#dev-env) and see what you're getting? I'm at `36` now :)

**Comment by TeddyGavi** [comment] 2023-07-20 20:37
32 now.... :confused: 

![image](https://github.com/activist-org/activist/assets/102203363/21aad916-e5b4-451a-b24f-4ab5285aeb02)

**Comment by luuu-xu** [comment] 2023-07-20 20:46
I have **36**. And I also found out that in `/frontend`, if I ran `npm install` to install packages, and run `yarn nuxi postinstall`. I will get an error `ERROR  Cannot find module 'pinia/dist/pinia.mjs`. But if I delete my `node_modules` and reinstall them with `yarn install`, then I can successfully run `yarn nuxi postinstall` and `yarn nuxi typecheck`. Is this the correct behavior?

<img width="376" alt="Screenshot 2023-07-20 at 16 42 38" src="https://github.com/activist-org/activist/assets/97932191/1a1a0e6e-8708-4af5-a5e6-a3867dc0f38c">

**Comment by andrewtavis** [comment] 2023-07-20 20:55
Confusing... Can you think of any extensions we might be missing, @TeddyGavi? I've got the same as @luuu-xu:

```bash
20  components/Card/CardSearchResult.vue:11
6  components/Grid/GridGithubShields.vue:3
1  components/Image/ImageGithubShield.vue:3
1  components/Menu/MenuMobileHeader.vue:9
1  components/Menu/MenuMobileSelector.vue:6
3  components/Sidebar/Sidebar.vue:13
3  layouts/event.vue:82 # ⬅️ one more
1  pages/events/brandenburg-gate-climate-demo.vue:70
```

**Comment by TeddyGavi** [comment] 2023-07-20 21:08
Aha! I have 36 now! So the real culprit must be the heaviest thing in the universe... 

> node_modules...

I followed your steps @luuu-xu and I got 36. I am going on a limb here ... that given the types are statically generated and I hadn't done a full clean of `node_modules` in some time (or ran docker as that presumably does `yarn install && yarn cache clean`) . The packages and exported types that were available were not the same across all of our machines. Possibly? 

It would be great to confirm this with at least one other! :smile: Then we can update the docs accordingly.

**Comment by andrewtavis** [comment] 2023-07-20 21:15
You could write into [Development](https://app.element.io/#/room/!CRgLpGeOBNwxYCtqmK:matrix.org) to see if someone can confirm? We'll all need to be switching over to Docker with an example database here soon anyway, so these Docker vs. direct yarn issues should be a thing of the past soon :)

**Comment by andrewtavis** [comment] 2023-07-22 06:29
I'd say let's not worry too much about a fourth person getting a consistent `yarn nuxi typecheck` output so long as we all get a consistent output again :) Now that #236 is closed I'm getting the following:

```
Found 29 errors in 6 files.

Errors  Files
    20  components/Card/CardSearchResult.vue:11
     1  components/Menu/MenuMobileHeader.vue:9
     1  components/Menu/MenuMobileSelector.vue:6
     3  components/Sidebar/Sidebar.vue:13
     3  layouts/event.vue:82
     1  pages/events/brandenburg-gate-climate-demo.vue:70
```

**Comment by andrewtavis** [comment] 2023-07-22 12:33
If we have the same counts, then we can go ahead and make the rest of the issues :) Looks like `CardSearchResult.vue` should be an error in itself 😅 Let's wait on me merging the two PRs that are passing tests beforehand though :)

**Comment by andrewtavis** [comment] 2023-07-27 21:00
After the most recent changes I'm now at the following, @TeddyGavi and @luuu-xu:

```
Found 24 errors in 12 files.

Errors  Files
     1  components/card/CardConnect.vue:96
     1  components/card/CardFeedItem.vue:41
     2  components/card/CardGetInvolved.vue:64
     3  components/card/CardSearchResult.vue:183
     1  components/landing/LandingContent.vue:160
     4  components/modal/ModalImage.vue:9
     1  layouts/event.vue:91
     3  pages/events/brandenburg-gate-climate-demo.vue:47
     1  pages/events/index.vue:34
     3  pages/home/index.vue:43
     1  pages/organizations/index.vue:32
     3  pages/organizations/tech-from-below.vue:40
```

**Comment by andrewtavis** [comment] 2023-07-27 21:04
A bit confusing that we're down to `3` errors in `components/card/CardSearchResult.vue` from `20` 🤔 This is confirmed by the errors I'm seeing in file itself though.

**Comment by andrewtavis** [comment] 2023-07-27 21:37
Just added TS to the composition API files that were missing it, thus bringing me to:

```
Found 54 errors in 20 files.

Errors  Files
     1  components/card/CardConnect.vue:96
     1  components/card/CardFeedItem.vue:41
     2  components/card/CardGetInvolved.vue:64
     3  components/card/CardSearchResult.vue:183
     4  components/form/FormButtonStyledCheckbox.vue:14
     3  components/form/FormButtonStyledRadio.vue:16
     3  components/form/FormCheckbox.vue:7
     6  components/form/FormCheckboxGroup.vue:9
     3  components/form/FormRadio.vue:5
     6  components/form/FormRadioGroup.vue:6
     3  components/form/FormSearch.vue:8
     1  components/landing/LandingContent.vue:160
     4  components/modal/ModalImage.vue:9
     2  components/selector/SelectorLanguage.vue:76
     1  layouts/event.vue:91
     3  pages/events/brandenburg-gate-climate-demo.vue:47
     1  pages/events/index.vue:34
     3  pages/home/index.vue:43
     1  pages/organizations/index.vue:32
     3  pages/organizations/tech-from-below.vue:40
```

**Comment by andrewtavis** [comment] 2023-07-30 22:14
I'm going to close this issue and put my current errors output in #211. I think we're done here, and that would be a good place to pick up the discussion of making the needed issues :)

**Closed by andrewtavis** 2023-07-30 22:14 UTC
Labels: help wanted, good first issue, refactor
