### ISSUE TITLE
Implement Pagination for Improved Performance and User Experience

### ISSUE THREAD

**Issue by momanyisamuel** [activist-org/activist#359] opened 2023-09-09 10:45 UTC
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This is an issue to implement pagination for large collections of data in activist-org API to enhance performance and improve the user experience. Django Rest Framework (DRF) offers built-in pagination classes that we can leverage to achieve this. This will allow activist-org API to limit the number of items returned in each response, making it more efficient for both server and client-side processing.

Reference: https://www.django-rest-framework.org/api-guide/pagination/

Happy to discuss any good ideas on how to best implement this

### Contribution

Happy to support someone on this issue or work on it myself

**Comment by IsaacDMz** [comment] 2023-09-11 01:26
Hi, I`m a newcomer and would love to work on this issue, its just change the backend? Pagination limits the number of items that go to the front end, would it be necessary to make changes to the frontend as well or just change the backend response?

**Comment by andrewtavis** [comment] 2023-09-11 05:13
Hey @IsaacDMz 👋 Thanks for your interest in activist :) Happy to assign you, and for this one it is just changes to the backend. We’ll be working on backend-frontend connections in a few weeks at our Saturday Code Night 🌙😊

**Comment by IsaacDMz** [comment] 2023-09-12 00:21
Someone can help me with this errors? I tried to solve this for hours and was unsuccessful?  
![image](https://github.com/activist-org/activist/assets/94393622/7b5524c5-a9cb-490c-9f18-f78844583068)

The containers postgres_db and nuxt_frontend are running ok, but the django_backend dont connect and always has this problem

**Comment by andrewtavis** [comment] 2023-09-12 03:52
What’s the command you’re running, @IsaacDMz? If you haven’t tried it, then `docker-compose up --build` is the normal first step :)

**Comment by IsaacDMz** [comment] 2023-09-12 12:57
Yeah, i run this comand. Apparently the problem is the connection to PostgreSQL. I'll try to run using Linux today

**Comment by andrewtavis** [comment] 2023-09-12 15:18
Thanks for reporting back, @IsaacDMz! :) Let us know if the issue doesn’t get better with Linux. You’ve copied over the `.env` as well, right? Just checking 😊

CC @wkyoshida who might have some suggestions here :)

**Comment by IsaacDMz** [comment] 2023-09-12 15:27
I dont know why this is hapenned. 
![image](https://github.com/activist-org/activist/assets/94393622/85bd7b45-edca-4f7c-aa42-0b9939daa608)
I'm using this env and also using linux in other pc i have the same problem
![image](https://github.com/activist-org/activist/assets/94393622/a4d7db60-4e85-4bff-8f7a-01c306baffdf)
![image](https://github.com/activist-org/activist/assets/94393622/15d1b0a2-715e-4de0-9ba7-2463a6a57456)
The command docker compose up -d --build run ok in ubuntu, but the docker compose up has this problem.
![image](https://github.com/activist-org/activist/assets/94393622/fbbce0da-31fb-471c-8dc2-699b54e270f6)
This is unusual behavior, is the first time it happens to me

**Comment by andrewtavis** [comment] 2023-09-12 16:49
I guess for now if you can get it running on Ubuntu with `docker-compose up -d --build` and this works for a dev env, then we should be good to start, and we can then check this in the coming days and get some feedback from the community :) I’m currently not in front of a computer until at least tomorrow night, so I’m also a bit limited in how much I can assist.

**Comment by andrewtavis** [comment] 2023-09-12 16:49
Let’s figure this out and update the docs though! 🚀😊

**Comment by IsaacDMz** [comment] 2023-09-12 17:42
hey @andrewtavis, the port of postgres was conflicted with other another container, @VinnyHS2 help to solve the problem. Just a docker system prune and rebuild the project solve this.

**Comment by andrewtavis** [comment] 2023-09-12 20:42
Glad to hear that all’s working, @IsaacDMz! And thanks for supporting, @VinnyHS2 😊 UTFPR team 🙌👏👏😊

**Comment by wkyoshida** [comment] 2023-09-13 00:34
> UTFPR team 🙌👏👏😊

hue

**Comment by andrewtavis** [comment] 2023-10-11 22:20
Closed via #414 :) Thanks for the improvements here, @IsaacDMz! Glad to have this finished up! 🚀

**Closed by andrewtavis** 2023-10-11 22:20 UTC
Labels: feature, help wanted, good first issue
