### ISSUE TITLE
docker-compose up --build failed

### ISSUE THREAD

**Issue by purupurupu** [activist-org/activist#55] opened 2023-02-03 05:40 UTC
### Terms

- [X] I have searched [open and closed issues](https://github.com/activist-org/activist/issues?q=is%3Aissue)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

I'm trying to contribute to OSS for the first time.
I'm getting an error with docker-compose up --build, can you merge the latest DockerFile?

The error looks like this.

```
❯ docker-compose up --build
[+] Building 1.8s (13/20)                                                       
 => [activist_backend internal] load build definition from Dockerfile      0.0s
 => => transferring dockerfile: 221B                                       0.0s
 => [nuxt_dev internal] load build definition from Dockerfile              0.0s
 => => transferring dockerfile: 201B                                       0.0s
 => [activist_backend internal] load .dockerignore                         0.0s
 => => transferring context: 2B                                            0.0s
 => [nuxt_dev internal] load .dockerignore                                 0.0s
 => => transferring context: 2B                                            0.0s
 => [activist_backend internal] load metadata for docker.io/library/pytho  1.6s
 => [nuxt_dev internal] load metadata for docker.io/library/node:19-alpin  1.5s
 => [nuxt_dev internal] load build context                                 0.0s
 => => transferring context: 9.88kB                                        0.0s
 => CANCELED [nuxt_dev 1/6] FROM docker.io/library/node:19-alpine@sha256:  0.1s
 => => resolve docker.io/library/node:19-alpine@sha256:19d89f49db981638a4  0.0s
 => => sha256:19d89f49db981638a413518ee405e1f50c60b4dbcc0 1.43kB / 1.43kB  0.0s
 => => sha256:9808a976c76cbafda84b95b4f295989604127f0b9af 1.16kB / 1.16kB  0.0s
 => => sha256:0daa9d7cca95a5013286df640a183eca837081a6765 6.45kB / 6.45kB  0.0s
 => [activist_backend internal] load build context                         0.0s
 => => transferring context: 9.88kB                                        0.0s
 => CANCELED [activist_backend 1/6] FROM docker.io/library/python:3.11.1-  0.0s
 => => resolve docker.io/library/python:3.11.1-alpine3.16@sha256:093bfc93  0.0s
 => => sha256:093bfc93121f76923bc68086452b807b3b26d3a663a 1.65kB / 1.65kB  0.0s
 => => sha256:37cb9fb2843ba9b4c192b02f5c78df6f36f46ebe6f4 1.37kB / 1.37kB  0.0s
 => => sha256:77ff935df433fd459e7af735b81d0eae9a8d09f14fc 7.16kB / 7.16kB  0.0s
 => CACHED [activist_backend 2/6] WORKDIR /app                             0.0s
 => CACHED [activist_backend 3/6] RUN pip install gunicorn                 0.0s
 => ERROR [activist_backend 4/6] COPY requirements.txt ./                  0.0s
------
 > [activist_backend 4/6] COPY requirements.txt ./:
------
failed to solve: failed to compute cache key: "/requirements.txt" not found: not found
```

Also, I think two points exist.
- Correct the path specification of requirement.txt in backend/DockerFile.
- psycopg==2-2.9.5 is not exist.

I'm not good at English, but I'm glad you get the message.

**Comment by andrewtavis** [comment] 2023-02-03 08:07
Hi @purupurupu, thanks for writing!

No stress on English — I understood you very clearly :) The docker files in the repo are the current ones I'm using. When I run the dev environment I just run `docker-compose up`, which then gives me the frontent on `http://localhost:3000/`. The backend currently isn't a priority and is broken as there's no `SECRET_KEY` within the Django files.

That it's not working with `docker-compose up --build` is a problem though. Will look into this, or let me know if you have any suggestions!

**Comment by andrewtavis** [comment] 2023-02-04 00:21
@purupurupu, documenting some of the changes I made in 8ce9a98 more thoroughly:

- `COPY ./backend/requirements.txt /app` solves the issue of not being able to find `requirements.txt`
    - I'm not sure why `./backend` is required, but `./frontend` is not in the other one (maybe based on images?)
- Switched `psycopg2` to `psycopg2-binary`
    - The latter is not for deployment and the `Dockerfile` would need to be expanded to use the former, but then we're not using the backend at the moment
- Moved `gunicorn` to `requirements.txt` so it's not installed via a step in the `Dockerfile`
- Added some simple comments to the docker files

I was just able to run `docker-compose up --build` and then jump to `http://localhost:3000/`. There doubtless is more work to be done, but I think that this at least allows for the other command now and will avoid some confusion 😊

Let me know what you think!

**Comment by purupurupu** [comment] 2023-02-04 13:50
@andrewtavis 
Thanks for the quick response!!!
I think it will be easier for contributors if that very thing is resolved.

**Comment by andrewtavis** [comment] 2023-02-04 18:42
Thanks again for sending along the issue, @purupurupu! Will close it now :)

**Comment by dkroll713** [comment] 2023-02-14 00:29
Hi @andrewtavis , I am running into a similar issue. I'd like to contribute but I'm running into issues running `docker-compose up --build` - but not the same issues already posted.

Here is what I'm running into:

![image](https://user-images.githubusercontent.com/41023883/218601708-12886090-0244-4625-bd5a-51a556ba06b5.png)

I thought it might be due to some conflicts between VirtualBox and Docker so I tried using WSL and ran into the same issue:

![image](https://user-images.githubusercontent.com/41023883/218605541-0c4ed88a-e19d-4d69-8e8e-e19223e1b825.png)

**Comment by andrewtavis** [comment] 2023-02-14 09:56
Hi @dkroll713 :) Thanks for your interest in contributing! Let me take a look into this and hopefully we can figure it out 😊

**Comment by andrewtavis** [comment] 2023-02-14 20:52
@dkroll713, 6f662ca is a very minor change that might help with this. As Nuxt not being found is the issue, it might be that some of the frontend dependencies are not being found properly. That commit adds the full relative path to `package.json`. Could you check and see if this works, and if not I'll head back to the drawing board?

**Comment by dkroll713** [comment] 2023-02-14 23:14
@andrewtavis that did not do it for me - I'm getting the same error. In case this helps diagnose it, I'm using Ubuntu 20.04 and confirmed it's not a Docker issue by successfully spinning up some other containers.

**Comment by andrewtavis** [comment] 2023-02-14 23:38
@dkroll713, sorry it's still not working :( Does `docker-compose up` without `--build` work for some initial work and playing around with the code while we work on this?

**Comment by dkroll713** [comment] 2023-02-15 00:14
@andrewtavis same error 🙃

**Comment by andrewtavis** [comment] 2023-02-15 06:57
Wonderful, @dkroll713 🙃 I'm limited in my ability to look into this for the remainder of the week sadly, but will look into it on Monday. Apologies that there'll be such a delay.

**Comment by andrewtavis** [comment] 2023-02-15 17:12
Something that could help is adding `node_modules` to the frontend volumes in `docker-compose.yml`.

I’ll test how to get this set up properly later on, but volumes could be hiding the node modules (see [SO answer](https://stackoverflow.com/a/72011761)).

**Comment by andrewtavis** [comment] 2023-02-22 17:32
@dkroll713, [82dfb27](https://github.com/activist-org/activist/commit/82dfb27298eb46908137db7bb607a1ed6e0b6a03) includes a minor change to the `docker-compose.yml` that might fix this as maybe the `node_modules` weren't in the volume. Could you let me know if that helps? 🙏

**Comment by wkyoshida** [comment] 2023-03-08 01:59
Created #74 which hopefully resolves the issue here!
Added some comments in the PR as well with some explanations. Let me know if you'd like me to clarify anything :+1:

**Comment by andrewtavis** [comment] 2023-03-08 14:22
Thanks for the help with this pressing issue, @wkyoshida! Really appreciate you jumping in so quickly and also for all the explanations/documentation for why we have the setup we have now :)

@dkroll713, if you can let me know if it works for you now I'd be much obliged. Sorry that I wasn't able to fix it in a reasonable time, but then it's hard when you can't reproduce. Thanks again for your interest in activist :)

Closing this now 😊

**Closed by andrewtavis** 2023-03-08 14:23 UTC
Labels: bug

**Comment by andrewtavis** [comment] 2023-03-15 15:58
@wkyoshida, checking on if one of the changes that you made can be reverted as I'm realizing that hot reloading is now not working :)

You deleted the following three lines in the `frontend` section of [docker-compose.yml](https://github.com/activist-org/activist/blob/main/docker-compose.yml):

```
volumes:
  - ./frontend/:/app
  - ./frontend/:/node_modules
```

In [your explanation](https://github.com/activist-org/activist/pull/74#discussion_r1128860354) you specifically mentioned that the problems above were being caused by the `- ./frontend/:/node_modules` line that was deleting the `node_modules` and thus Nuxt for new contributors. Looking at the solutions for hot reloading in Docker for Vue based apps in [this SO question](https://stackoverflow.com/questions/59224130/docker-compose-hot-reloading-does-not-work-with-vuejs-app), I figured out that adding back in the following without the `node_modules` line is enough to get hot reloading up and running again (I think this is actually where I first got these lines 🤔):

```
volumes:
  - ./frontend/:/app
```

Do you see a real issue with having the above in there as well? Really would like to set it up so that we can get the page directly reflecting the current changes so that the dev experience can be snappy 😊

**Comment by andrewtavis** [comment] 2023-03-15 16:54
These lines were added back in in [a8eb48c](https://github.com/activist-org/activist/commit/a8eb48cc29841bb15e485e51d31d1615b75594bc), but let me know if they should be removed or if there's a better way of adding in hot reloading than this 😊

**Comment by andrewtavis** [comment] 2023-03-16 11:02
@wkyoshida, af10033 reverted the change of [a8eb48c](https://github.com/activist-org/activist/commit/a8eb48cc29841bb15e485e51d31d1615b75594bc) as the issue came back for someone as seen in #34. I guess for now I can uncomment the frontend volumes in [docker-compose.yml](https://github.com/activist-org/activist/blob/main/docker-compose.yml) when I want hot reloading, but then I wonder if others need to restart the docker image to see their changes? 🤔 Would be great if we had hot reloading on save working out of the box for folks :)

Any ideas on this would be welcome!

**Comment by wkyoshida** [comment] 2023-03-22 01:28
Hey @andrewtavis ! 

Gotchu! Now, I understand what you actually had in mind initially. Didn't realize you were going for hot-reloading here. And yes, contributors would have to rebuild the Docker image in order to see their changes. Hopefully #81 now though allows for what you were looking for. It adds the following under `volumes:`

- `/app/node_modules`

Essentially it is the same as saying `{EMPTY_VOLUME_CREATED_BY_DOCKER}:/app/node_modules`, as volumes have the syntax of `SOURCE:TARGET`. In doing so, this isolates that `node_modules` in its own volume, so when `./frontend:/app` attaches the frontend code as a volume to the container, it doesn't override the `/app/node_modules` directory. Hopefully this makes sense! 

The idea is similar to those presented in these articles I've found on hot-reloading:
- [1](https://medium.com/@kartikio/setup-node-ts-local-development-environment-with-docker-and-hot-reloading-922db9016119)
- [2](https://www.freecodecamp.org/news/how-to-enable-live-reload-on-docker-based-applications/)

**Comment by andrewtavis** [comment] 2023-03-22 12:40
Hey @wkyoshida! Thanks so much for the further fix for this and the explanation 😊 In comparing the codes and reading what you wrote it does make sense! Hot-reloading definitely improves my dev experience, so really happy to get it up and running :)
