### ISSUE TITLE
Landing page images disappearing on reload

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#223] opened 2023-07-14 21:55 UTC
### Terms

- [X] I have searched all [open bug reports](https://github.com/activist-org/activist/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

A general problem I've been realizing on the [landing page](https://activist.org/) for some time now is that when the page is reloaded a couple times the fist images next to `Get active`, `Get organized` and `Grow your organization` will stop loading and we'll instead see their alternate text.

**Ways to reproduce**
- Go to the home page and reload a couple of times to see the images disappear

Would be great if we could get this solved as its doubtless causing some non-ideal impressions.

**Comment by Wholesomebruh** [comment] 2023-07-15 06:47
Hi @andrewtavis , unable to reproduce the error. Please recheck and guide.

**Comment by andrewtavis** [comment] 2023-07-15 07:49
Hey @Wholesomebruh 👋 Thanks for writing in about this :) Glad that you’re not effected by this as well, I guess 😅 What’s your browser, out of curiosity?

**Comment by andrewtavis** [comment] 2023-07-15 08:01
Also super helpful to talk to you about this, as I now have a better definition of the bug 🐞 It would happen "randomly" as I was clicking around, but now I'm seeing that it's specifically after you navigate to a localized URL. To reproduce (checked on Chrome and Firefox):

- Go to the landing page
- Click the activist logo in the top left corner
  - This switches it to the english localization for me
  - You can also select a localization via the language selector at the top
- Reload the page again and the images disappear

**Comment by andrewtavis** [comment] 2023-07-15 08:05
Note also that the roadmap and FAQ page images are not experiencing this problem, so they work on localized and unlocalized URLs :)

**Comment by andrewtavis** [comment] 2023-07-15 08:06
If you have interest in implementing a solution I'd be happy to assign you, @Wholesomebruh! We can discuss the solution further of course 😊

**Comment by Wholesomebruh** [comment] 2023-07-15 10:08
Hey @andrewtavis , from what I can see, there is issue in localization implementation. 

For the image :
`https://activist.org/images/content_pages/art/get_active_dark.png` works totally fine, whereas after localization , url changes to `https://activist.org/en/images/content_pages/art/get_active_dark.png` which gives the error. Same is with french and german language. 

For resolving the issue, I tried to run code on my system , but I am unable to install the library .
![image](https://github.com/activist-org/activist/assets/109906215/ff45e1ad-3c0c-4ace-96e0-6cbb817c6f66)
 Guide me through the process.

**Comment by andrewtavis** [comment] 2023-07-15 20:01
@Wholesomebruh, assigned you so we can work on it :) What was the command that you ran in the terminal to get it up and running? The [contribution guidelines](https://github.com/activist-org/activist/blob/main/CONTRIBUTING.md) has a section on the [development environment](https://github.com/activist-org/activist/blob/main/CONTRIBUTING.md#dev-env) that details how to set it up. 

If that's not what you tried, could you report back and let me know if that's working?

**Comment by Wholesomebruh** [comment] 2023-07-15 21:59
Hey @andrewtavis ,
thank you so much for assigning , eventually I am unable to help as my system doesn't allows docker. If possible just try adding a "/" infront of images in 
```bash 
imageURL="images/content_pages/art/get_active"
```
in `https://github.com/activist-org/activist/blob/main/frontend/pages/index.vue` line 16,27,38. Please unassign me.

**Comment by andrewtavis** [comment] 2023-07-15 22:01
Hey @Wholesomebruh :) You'd be welcome to use the GitHub UI to send along this PR 😊 If it doesn't work I'll try to find a different solution.

**Comment by andrewtavis** [comment] 2023-07-15 22:02
We'll be able to check in the deployment previews that are generated by PRs to see if it's working, and if so I'd be happy to merge 🙃

**Comment by andrewtavis** [comment] 2023-07-15 22:08
Checking the code, this definitely seems to be the appropriate change, @Wholesomebruh. All the other images are working, and they have a `/` before `images/content/...`. I'd add that beyond lines 16, 27 and 38 in [frontend/pages/index.vue](https://github.com/activist-org/activist/blob/main/frontend/pages/index.vue), the change also needs to be made at line 50 😊

**Comment by andrewtavis** [comment] 2023-07-15 22:10
Hope you choose to contribute the changes! You did do all the work :)

**Comment by Wholesomebruh** [comment] 2023-07-15 22:11
Did the "/" removed the bug?

**Comment by andrewtavis** [comment] 2023-07-15 22:15
I believe it will :) I checked the code and for example the roadmap page has the following with `/images/content_pages/...` as you suggested:

https://github.com/activist-org/activist/blob/d764516af41c804b4dac310bdb2e79a0bc511dfa/frontend/pages/about/roadmap.vue#L14

I can't check this locally as I think that on my localhost the images are being sent in a more consistent manner that they're not when in production, but your suggestion seems to be the right one.

If you open a PR with the changes to the four lines we'll be able to test to see if it works in production :)

**Closed** 2023-07-15 22:20 UTC
Labels: bug, help wanted, good first issue, -priority-

**Comment by Wholesomebruh** [comment] 2023-07-15 22:23
Thank you sir , you are so supportive.I was just going to leave the issue.
Thanks again .

**Comment by andrewtavis** [comment] 2023-07-15 22:26
Thank you, @Wholesomebruh! This was a very solid contribution. You first checked my issue and helped me diagnose it, then came up with the solution, and then implemented it. The result: https://activist.org/en/ 🚀😊

I can confirm that this issue is closed 🥳
